### ISSUE TITLE
后台登录问题

### ISSUE THREAD

**Issue by phpcws** [winerQin/yesnophp#1]
后台登录时，提示登录成功，但是还是跳转到登录页面，很奇怪。

**Comment by winerQin** [comment]
出现这个问题是因为域名导致的问题。
在ms_config表中有一个管理后台cookie保存的域：admin_cookie_domain。请将它设置为当前登录的域名。

比如，你当前管理员后台的域名为：backend.yesnophp.com
那么，请将它设置为 .backend.yesnophp.com

如果，你之前没有设置。请记录将 redis 缓存清空一下。避免，缓存未生效。redis 缓存清空请登录redis服务器执行清除命令。后续，我会在配置中增加一个配置文件是否使用 redis 缓存的选项。另外，代码最近几天做了更新。你可以使用最新版。数据库也做了小调整。

祝你使用愉快。

**Comment by phpcws** [comment]
@winerQin 感谢回答，ms_config表都已经配置了。可能是redis没清，我再测试下.....

**Comment by phpcws** [comment]
@winerQin 使用您的后台，又遇到一些小问题，如果有时间帮忙看下。问题->  登录成功，提示： 2000005  URL地址有误。我后台登录成功跳转的地址：http://backend.yaf.com/backend/Index/index   数据库中的配置文件域名地址也改了，管理员cookie作用域也改了。本地的伪静态也开启了。其他不知道还有哪些问题？

**Comment by winerQin** [comment]
你稍等。我看看是不是我最近调整了代码导致的。最迟明天给你答复。

**Comment by winerQin** [comment]
代码已经更新了。造成 BUG 的原因是因为我把我的单域名版的 YesnoPHP 复制过来的时候，忘记了做了测试。谢谢你的反馈。

你只需要把本地代码更新到最新版本即可。

**Comment by phpcws** [comment]
@winerQin 谢谢，现在可以登录了
